spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/websocketflutter
    driver-class-name: org.mariadb.jdbc.Driver
    username: websocketuser
    password: ckdgns12
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update